Running test: gcd #1... PASS
Running test: f (x) 34... PASS
Running test: f (n) n + 1... PASS
Running test: f (n) g(n-3); g (x) x - 1... PASS
Running test: fact (n) if n = 0 then 1 else n * fac...... PASS
Running test: fib (n) if n < 2 then n else fib (n-1...... PASS
Running test: phi (n) (count ((Î» (k) coprime (k,n))...... ERROR
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Identifier k not found.
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at PdpTestSuite$TestCase.run(PdpTestSuite.java:86)
	at PdpTestSuite.runTests(PdpTestSuite.java:45)
	at PdpPgmTests.main(PdpPgmTests.java:113)
Caused by: java.lang.IllegalArgumentException: Identifier k not found.
	at IdentifierExpImpl.value(IdentifierExpImpl.java:56)
	at CallExpImpl.value(CallExpImpl.java:80)
	at LambdaExpImpl.value(LambdaExpImpl.java:65)
	at CallExpImpl.value(CallExpImpl.java:80)
	at CallExpImpl.value(CallExpImpl.java:70)
	at LambdaExpImpl.value(LambdaExpImpl.java:65)
	at Programs.run(Programs.java:36)
	at PdpPgmTests.lambda$addTest$40(PdpPgmTests.java:132)
	at PdpPgmTests$$Lambda$2/471910020.get(Unknown Source)
	at PdpTestSuite$TestCase.lambda$run$38(PdpTestSuite.java:84)
	at PdpTestSuite$TestCase$$Lambda$3/1826771953.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Running test: f (n) g (n);g (f) if f < 2 then i (f)...... ERROR
java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at PdpTestSuite$TestCase.run(PdpTestSuite.java:86)
	at PdpTestSuite.runTests(PdpTestSuite.java:45)
	at PdpPgmTests.main(PdpPgmTests.java:113)
Caused by: java.lang.UnsupportedOperationException
	at BaseExpVal.asFunction(BaseExpVal.java:58)
	at CallExpImpl.value(CallExpImpl.java:70)
	at ArithmeticExpImpl.value(ArithmeticExpImpl.java:88)
	at LambdaExpImpl.value(LambdaExpImpl.java:65)
	at CallExpImpl.value(CallExpImpl.java:84)
	at IfExpImpl.value(IfExpImpl.java:82)
	at LambdaExpImpl.value(LambdaExpImpl.java:65)
	at CallExpImpl.value(CallExpImpl.java:84)
	at LambdaExpImpl.value(LambdaExpImpl.java:65)
	at Programs.run(Programs.java:36)
	at PdpPgmTests.lambda$addTest$40(PdpPgmTests.java:132)
	at PdpPgmTests$$Lambda$2/471910020.get(Unknown Source)
	at PdpTestSuite$TestCase.lambda$run$38(PdpTestSuite.java:84)
	at PdpTestSuite$TestCase$$Lambda$3/1826771953.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Running test: # Inner product of two vectors.# # Cr...... ERROR
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Identifier i not found.
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at PdpTestSuite$TestCase.run(PdpTestSuite.java:86)
	at PdpTestSuite.runTests(PdpTestSuite.java:45)
	at PdpPgmTests.main(PdpPgmTests.java:113)
Caused by: java.lang.IllegalArgumentException: Identifier i not found.
	at IdentifierExpImpl.value(IdentifierExpImpl.java:56)
	at LambdaExpImpl.value(LambdaExpImpl.java:65)
	at CallExpImpl.value(CallExpImpl.java:80)
	at CallExpImpl.value(CallExpImpl.java:80)
	at LambdaExpImpl.value(LambdaExpImpl.java:65)
	at Programs.run(Programs.java:36)
	at PdpPgmTests.lambda$addTest$40(PdpPgmTests.java:132)
	at PdpPgmTests$$Lambda$2/471910020.get(Unknown Source)
	at PdpTestSuite$TestCase.lambda$run$38(PdpTestSuite.java:84)
	at PdpTestSuite$TestCase$$Lambda$3/1826771953.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Running test: # Inner product of two vectors.# # Cr...... ERROR
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Identifier i not found.
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at PdpTestSuite$TestCase.run(PdpTestSuite.java:86)
	at PdpTestSuite.runTests(PdpTestSuite.java:45)
	at PdpPgmTests.main(PdpPgmTests.java:113)
Caused by: java.lang.IllegalArgumentException: Identifier i not found.
	at IdentifierExpImpl.value(IdentifierExpImpl.java:56)
	at LambdaExpImpl.value(LambdaExpImpl.java:65)
	at CallExpImpl.value(CallExpImpl.java:80)
	at CallExpImpl.value(CallExpImpl.java:80)
	at LambdaExpImpl.value(LambdaExpImpl.java:65)
	at Programs.run(Programs.java:36)
	at PdpPgmTests.lambda$addTest$40(PdpPgmTests.java:132)
	at PdpPgmTests$$Lambda$2/471910020.get(Unknown Source)
	at PdpTestSuite$TestCase.lambda$run$38(PdpTestSuite.java:84)
	at PdpTestSuite$TestCase$$Lambda$3/1826771953.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Running test: # Church numerals## The natural numbe...... ERROR
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Identifier x not found.
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at PdpTestSuite$TestCase.run(PdpTestSuite.java:86)
	at PdpTestSuite.runTests(PdpTestSuite.java:45)
	at PdpPgmTests.main(PdpPgmTests.java:113)
Caused by: java.lang.IllegalArgumentException: Identifier x not found.
	at IdentifierExpImpl.value(IdentifierExpImpl.java:56)
	at LambdaExpImpl.value(LambdaExpImpl.java:65)
	at LambdaExpImpl.value(LambdaExpImpl.java:65)
	at CallExpImpl.value(CallExpImpl.java:84)
	at CallExpImpl.value(CallExpImpl.java:70)
	at CallExpImpl.value(CallExpImpl.java:80)
	at LambdaExpImpl.value(LambdaExpImpl.java:65)
	at LambdaExpImpl.value(LambdaExpImpl.java:65)
	at LambdaExpImpl.value(LambdaExpImpl.java:65)
	at CallExpImpl.value(CallExpImpl.java:84)
	at IfExpImpl.value(IfExpImpl.java:82)
	at LambdaExpImpl.value(LambdaExpImpl.java:65)
	at CallExpImpl.value(CallExpImpl.java:84)
	at CallExpImpl.value(CallExpImpl.java:80)
	at IfExpImpl.value(IfExpImpl.java:82)
	at LambdaExpImpl.value(LambdaExpImpl.java:65)
	at CallExpImpl.value(CallExpImpl.java:84)
	at CallExpImpl.value(CallExpImpl.java:80)
	at IfExpImpl.value(IfExpImpl.java:82)
	at LambdaExpImpl.value(LambdaExpImpl.java:65)
	at CallExpImpl.value(CallExpImpl.java:84)
	at CallExpImpl.value(CallExpImpl.java:80)
	at IfExpImpl.value(IfExpImpl.java:82)
	at LambdaExpImpl.value(LambdaExpImpl.java:65)
	at CallExpImpl.value(CallExpImpl.java:84)
	at CallExpImpl.value(CallExpImpl.java:80)
	at CallExpImpl.value(CallExpImpl.java:80)
	at LambdaExpImpl.value(LambdaExpImpl.java:65)
	at Programs.run(Programs.java:36)
	at PdpPgmTests.lambda$addTest$40(PdpPgmTests.java:132)
	at PdpPgmTests$$Lambda$2/471910020.get(Unknown Source)
	at PdpTestSuite$TestCase.lambda$run$38(PdpTestSuite.java:84)
	at PdpTestSuite$TestCase$$Lambda$3/1826771953.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Running test: # Church numerals## The natural numbe...... ERROR
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Identifier x not found.
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at PdpTestSuite$TestCase.run(PdpTestSuite.java:86)
	at PdpTestSuite.runTests(PdpTestSuite.java:45)
	at PdpPgmTests.main(PdpPgmTests.java:113)
Caused by: java.lang.IllegalArgumentException: Identifier x not found.
	at IdentifierExpImpl.value(IdentifierExpImpl.java:56)
	at LambdaExpImpl.value(LambdaExpImpl.java:65)
	at LambdaExpImpl.value(LambdaExpImpl.java:65)
	at CallExpImpl.value(CallExpImpl.java:84)
	at CallExpImpl.value(CallExpImpl.java:70)
	at CallExpImpl.value(CallExpImpl.java:80)
	at LambdaExpImpl.value(LambdaExpImpl.java:65)
	at LambdaExpImpl.value(LambdaExpImpl.java:65)
	at LambdaExpImpl.value(LambdaExpImpl.java:65)
	at CallExpImpl.value(CallExpImpl.java:84)
	at IfExpImpl.value(IfExpImpl.java:82)
	at LambdaExpImpl.value(LambdaExpImpl.java:65)
	at CallExpImpl.value(CallExpImpl.java:84)
	at CallExpImpl.value(CallExpImpl.java:80)
	at IfExpImpl.value(IfExpImpl.java:82)
	at LambdaExpImpl.value(LambdaExpImpl.java:65)
	at CallExpImpl.value(CallExpImpl.java:84)
	at CallExpImpl.value(CallExpImpl.java:80)
	at IfExpImpl.value(IfExpImpl.java:82)
	at LambdaExpImpl.value(LambdaExpImpl.java:65)
	at CallExpImpl.value(CallExpImpl.java:84)
	at CallExpImpl.value(CallExpImpl.java:80)
	at IfExpImpl.value(IfExpImpl.java:82)
	at LambdaExpImpl.value(LambdaExpImpl.java:65)
	at CallExpImpl.value(CallExpImpl.java:84)
	at CallExpImpl.value(CallExpImpl.java:80)
	at IfExpImpl.value(IfExpImpl.java:82)
	at LambdaExpImpl.value(LambdaExpImpl.java:65)
	at CallExpImpl.value(CallExpImpl.java:84)
	at CallExpImpl.value(CallExpImpl.java:80)
	at IfExpImpl.value(IfExpImpl.java:82)
	at LambdaExpImpl.value(LambdaExpImpl.java:65)
	at CallExpImpl.value(CallExpImpl.java:84)
	at CallExpImpl.value(CallExpImpl.java:80)
	at CallExpImpl.value(CallExpImpl.java:80)
	at LambdaExpImpl.value(LambdaExpImpl.java:65)
	at Programs.run(Programs.java:36)
	at PdpPgmTests.lambda$addTest$40(PdpPgmTests.java:132)
	at PdpPgmTests$$Lambda$2/471910020.get(Unknown Source)
	at PdpTestSuite$TestCase.lambda$run$38(PdpTestSuite.java:84)
	at PdpTestSuite$TestCase$$Lambda$3/1826771953.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Running test: # Given lo and hi, returns the number...... ERROR
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Identifier p not found.
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at PdpTestSuite$TestCase.run(PdpTestSuite.java:86)
	at PdpTestSuite.runTests(PdpTestSuite.java:45)
	at PdpPgmTests.main(PdpPgmTests.java:113)
Caused by: java.lang.IllegalArgumentException: Identifier p not found.
	at IdentifierExpImpl.value(IdentifierExpImpl.java:56)
	at CallExpImpl.value(CallExpImpl.java:80)
	at LambdaExpImpl.value(LambdaExpImpl.java:65)
	at CallExpImpl.value(CallExpImpl.java:80)
	at LambdaExpImpl.value(LambdaExpImpl.java:65)
	at CallExpImpl.value(CallExpImpl.java:84)
	at CallExpImpl.value(CallExpImpl.java:80)
	at LambdaExpImpl.value(LambdaExpImpl.java:65)
	at Programs.run(Programs.java:36)
	at PdpPgmTests.lambda$addTest$40(PdpPgmTests.java:132)
	at PdpPgmTests$$Lambda$2/471910020.get(Unknown Source)
	at PdpTestSuite$TestCase.lambda$run$38(PdpTestSuite.java:84)
	at PdpTestSuite$TestCase$$Lambda$3/1826771953.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Running test: # Given lo and hi, returns the number...... ERROR
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Identifier p not found.
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at PdpTestSuite$TestCase.run(PdpTestSuite.java:86)
	at PdpTestSuite.runTests(PdpTestSuite.java:45)
	at PdpPgmTests.main(PdpPgmTests.java:113)
Caused by: java.lang.IllegalArgumentException: Identifier p not found.
	at IdentifierExpImpl.value(IdentifierExpImpl.java:56)
	at CallExpImpl.value(CallExpImpl.java:80)
	at LambdaExpImpl.value(LambdaExpImpl.java:65)
	at CallExpImpl.value(CallExpImpl.java:80)
	at LambdaExpImpl.value(LambdaExpImpl.java:65)
	at CallExpImpl.value(CallExpImpl.java:84)
	at CallExpImpl.value(CallExpImpl.java:80)
	at LambdaExpImpl.value(LambdaExpImpl.java:65)
	at Programs.run(Programs.java:36)
	at PdpPgmTests.lambda$addTest$40(PdpPgmTests.java:132)
	at PdpPgmTests$$Lambda$2/471910020.get(Unknown Source)
	at PdpTestSuite$TestCase.lambda$run$38(PdpTestSuite.java:84)
	at PdpTestSuite$TestCase$$Lambda$3/1826771953.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Running test: # Binary search tree benchmark.## Cre...... ERROR
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Identifier key not found.
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at PdpTestSuite$TestCase.run(PdpTestSuite.java:86)
	at PdpTestSuite.runTests(PdpTestSuite.java:45)
	at PdpPgmTests.main(PdpPgmTests.java:113)
Caused by: java.lang.IllegalArgumentException: Identifier key not found.
	at IdentifierExpImpl.value(IdentifierExpImpl.java:56)
	at CallExpImpl.value(CallExpImpl.java:80)
	at CallExpImpl.value(CallExpImpl.java:80)
	at LambdaExpImpl.value(LambdaExpImpl.java:65)
	at CallExpImpl.value(CallExpImpl.java:70)
	at IfExpImpl.value(IfExpImpl.java:82)
	at LambdaExpImpl.value(LambdaExpImpl.java:65)
	at CallExpImpl.value(CallExpImpl.java:84)
	at IfExpImpl.value(IfExpImpl.java:80)
	at LambdaExpImpl.value(LambdaExpImpl.java:65)
	at CallExpImpl.value(CallExpImpl.java:84)
	at CallExpImpl.value(CallExpImpl.java:80)
	at LambdaExpImpl.value(LambdaExpImpl.java:65)
	at Programs.run(Programs.java:36)
	at PdpPgmTests.lambda$addTest$40(PdpPgmTests.java:132)
	at PdpPgmTests$$Lambda$2/471910020.get(Unknown Source)
	at PdpTestSuite$TestCase.lambda$run$38(PdpTestSuite.java:84)
	at PdpTestSuite$TestCase$$Lambda$3/1826771953.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Running test: # Binary search tree benchmark.## Cre...... ERROR
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Identifier key not found.
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at PdpTestSuite$TestCase.run(PdpTestSuite.java:86)
	at PdpTestSuite.runTests(PdpTestSuite.java:45)
	at PdpPgmTests.main(PdpPgmTests.java:113)
Caused by: java.lang.IllegalArgumentException: Identifier key not found.
	at IdentifierExpImpl.value(IdentifierExpImpl.java:56)
	at CallExpImpl.value(CallExpImpl.java:80)
	at CallExpImpl.value(CallExpImpl.java:80)
	at LambdaExpImpl.value(LambdaExpImpl.java:65)
	at CallExpImpl.value(CallExpImpl.java:70)
	at IfExpImpl.value(IfExpImpl.java:82)
	at LambdaExpImpl.value(LambdaExpImpl.java:65)
	at CallExpImpl.value(CallExpImpl.java:84)
	at IfExpImpl.value(IfExpImpl.java:80)
	at LambdaExpImpl.value(LambdaExpImpl.java:65)
	at CallExpImpl.value(CallExpImpl.java:84)
	at CallExpImpl.value(CallExpImpl.java:80)
	at LambdaExpImpl.value(LambdaExpImpl.java:65)
	at Programs.run(Programs.java:36)
	at PdpPgmTests.lambda$addTest$40(PdpPgmTests.java:132)
	at PdpPgmTests$$Lambda$2/471910020.get(Unknown Source)
	at PdpTestSuite$TestCase.lambda$run$38(PdpTestSuite.java:84)
	at PdpTestSuite$TestCase$$Lambda$3/1826771953.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
6 success(es) 0 failure(s) 10 error(s) 16 test(s) run